### ISSUE TITLE
Wishlist: Firestore + Redux gatsby starter

### ISSUE THREAD

**Issue by estherholleman** [muhajirframe/gatsby-starter-firebase#1]
Hi Muhammad, I'm struggling to get Firestore working together with Gatsby and Redux (with middleware (Redux Thunk)) using 'react-redux-firebase' and 'redux-firestore'. A reference error (self is not defined , due to a polyfill in firebase) occurs when trying to import firebase (initializeApp). I need to be able to read from and write to Firestore (and authentication too ideally). It would be great if you could make a starter on this! :-)

**Comment by muhajirframe** [comment]
Yo @estherholleman , check this out https://github.com/muhajirframe/gatsby-starter-redux-firebase

**Comment by estherholleman** [comment]
Wow, thank you @muhajirframe ! That was fast! Great idea to put the Firebase import statements in componentDidMount (importing Firebase appeared to be the problem in my attempts). I'd also never worked with createContext before, so that was interesting  :+1:  Thanks so much again! :D

**Comment by muhajirdev** [comment]
Okay, closing this issue 👍 . Let me know if you face another issue @estherholleman
