### ISSUE TITLE
Starter Fails To Start

### ISSUE THREAD

**Issue by Skillz4Killz** [muhajirframe/gatsby-starter-firebase#2]
Steps To Replicate: (Replicated Twice)

1. `gatsby new gog https://github.com/muhajirframe/gatsby-starter-firebase`
2. `cd gog`
3. `yarn develop`

```js
error UNHANDLED REJECTION


  Error: Cannot find module 'core-js/features/array/find'
  
  - loader.js:668 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:668:15
  
  - loader.js:591 Function.Module._load
    internal/modules/cjs/loader.js:591:27
  
  - loader.js:723 Module.require
    internal/modules/cjs/loader.js:723:19
  
  - helpers.js:14 require
    internal/modules/cjs/helpers.js:14:16
  
  - render-page.js:3 webpackUniversalModuleDefinition
    /gog/public/render-page.js:3:54
  
  - render-page.js:10 Object.<anonymous>
    /gog/public/render-page.js:10:3
  
  - loader.js:816 Module._compile
    internal/modules/cjs/loader.js:816:30
  
  - loader.js:827 Object.Module._extensions..js
    internal/modules/cjs/loader.js:827:10
  
  - loader.js:685 Module.load
    internal/modules/cjs/loader.js:685:32
  
  - loader.js:620 Function.Module._load
    internal/modules/cjs/loader.js:620:12
  
  - loader.js:723 Module.require
    internal/modules/cjs/loader.js:723:19
  
  - helpers.js:14 require
    internal/modules/cjs/helpers.js:14:16
  
  - worker.js:32 Promise
    [gog]/[gatsby]/dist/utils/worker.js:32:35
  
  - debuggability.js:313 Promise._execute
    [gog]/[bluebird]/js/release/debuggability.js:313:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [gog]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [gog]/[bluebird]/js/release/promise.js:79:10
```

```js
Home:gog Skillz$ node -v
v11.14.0
Home:gog Skillz$ gatsby -v
2.4.13
```

**Comment by muhajirdev** [comment]
Hi @Skillz4Killz,

Thanks for submitting the issue. Will take a look

**Comment by Skillz4Killz** [comment]
@muhajirdev Hey, Thank you!

I spent a few days debugging this as best as possible. I was able to narrow it down to 2 lines that are causing this. Commenting these lines actually stops all the errors from happening.

I filed some issues on their respective repos but still no response on them yet.
https://github.com/firebase/firebase-js-sdk/issues/1713
https://github.com/firebase/firebaseui-web-react/issues/63

In the layout/index.js
```js
const app = import('firebase/app')
```

In the containers/SignIn.js
```js
import { StyledFirebaseAuth } from 'react-firebaseui'
```

**Comment by josephkandi** [comment]
Still no fix for this? I see the linked issue is closed on the firebaseui page.

**Comment by Skillz4Killz** [comment]
@josephkandi I got it working simply by downgrading the firebase to 5.8.6. I am not sure if there has been a fix since then in firebase or gatsby.

**Comment by josephkandi** [comment]
I changed firebase to `5.8.6` but i get a different error regarding core-js, ` ERROR 

UNHANDLED REJECTION Cannot find module 'core-js/features/array/find'`

Then i did `yarn add core-js` as per and now i get a completely different error, `NHANDLED REJECTION Cannot find module 'core-js/modules/es6.array.filter'



  Error: Cannot find module 'core-js/modules/es6.array.filter'`.

When you follow the instructions on the `README.md` of this repo, does it work by just cloning and running `gatsby develop`?

**Comment by josephkandi** [comment]
Finally got it working, it important though that the version needs to be `5.9.0` not `^5.9.0`. I have `^5.9.0` and kept failing.

**Comment by Chiiip** [comment]
@josephkandi i did the same and it started working here. Thanks a lot!
